baseurl = "http://wawrowski.edu.pl/"
title = "Łukasz Wawrowski"
theme = "ghostwriter"
languageCode = "pl-pl"
copyright = "Łukasz Wawrowski"
disqusShortname = "lukaszwawrowski"
googleAnalytics = "UA-49771039-5"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Author]
    name = "Łukasz Wawrowski"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Łukasz Wawrowski"
    description = "Statystyczna ciekawość świata"
    github = "https://github.com/lwawrowski"
    linkedin = "https://linkedin.com/in/łukasz-wawrowski-2b106a149/"
    stackoverflow = "https://stackoverflow.com/users/1651832/lukasz89x"
    twitter = "https://twitter.com/wawrluk"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    highlightjsLang = ["r", "yaml", "javascript"]

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
    
[[menu.main]]
    name = "Publikacje"
    url = "/page/publikacje/"
    weight = 2

[[menu.main]]
    name = "Projekty"
    url = "/page/projekty/"
    weight = 3

[[menu.main]]
    name = "Dydaktyka"
    url = "/page/dydaktyka/"
    weight = 4
    
[[menu.main]]
    name = "Współpraca"
    url = "/page/wspolpraca/"
    weight = 5

[[menu.main]]
    name = "O mnie"
    url = "/page/about/"
    weight = 6
