<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>3 Regresja | Metody przetwarzania i analizy danych w R</title>
  <meta name="description" content="Materiały dydaktyczne do kursu Metody przetwarzania i analizy danych w R.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="3 Regresja | Metody przetwarzania i analizy danych w R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Materiały dydaktyczne do kursu Metody przetwarzania i analizy danych w R." />
  <meta name="github-repo" content="lwawrowski/analiza-danych-R" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 Regresja | Metody przetwarzania i analizy danych w R" />
  
  <meta name="twitter:description" content="Materiały dydaktyczne do kursu Metody przetwarzania i analizy danych w R." />
  

<meta name="author" content="Łukasz Wawrowski">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="testowanie-hipotez.html">
<link rel="next" href="grupowanie.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Metody przetwarzania i analizy danych w R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Wprowadzenie</a></li>
<li class="chapter" data-level="1" data-path="wprowadzenie-1.html"><a href="wprowadzenie-1.html"><i class="fa fa-check"></i><b>1</b> Wprowadzenie</a><ul>
<li class="chapter" data-level="1.1" data-path="wprowadzenie-1.html"><a href="wprowadzenie-1.html#narzedzie"><i class="fa fa-check"></i><b>1.1</b> Narzędzie</a></li>
<li class="chapter" data-level="1.2" data-path="wprowadzenie-1.html"><a href="wprowadzenie-1.html#cele-analiz"><i class="fa fa-check"></i><b>1.2</b> Cele analiz</a><ul>
<li class="chapter" data-level="1.2.1" data-path="wprowadzenie-1.html"><a href="wprowadzenie-1.html#eksporacja-danych"><i class="fa fa-check"></i><b>1.2.1</b> Eksporacja danych</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="testowanie-hipotez.html"><a href="testowanie-hipotez.html"><i class="fa fa-check"></i><b>2</b> Testowanie hipotez</a><ul>
<li class="chapter" data-level="2.1" data-path="testowanie-hipotez.html"><a href="testowanie-hipotez.html#hipoteza-statystyczna"><i class="fa fa-check"></i><b>2.1</b> Hipoteza statystyczna</a></li>
<li class="chapter" data-level="2.2" data-path="testowanie-hipotez.html"><a href="testowanie-hipotez.html#poziom-istotnosci-i-wartosc-p"><i class="fa fa-check"></i><b>2.2</b> Poziom istotności i wartość p</a></li>
<li class="chapter" data-level="2.3" data-path="testowanie-hipotez.html"><a href="testowanie-hipotez.html#testy-parametryczne-i-nieparametryczne"><i class="fa fa-check"></i><b>2.3</b> Testy parametryczne i nieparametryczne</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="regresja.html"><a href="regresja.html"><i class="fa fa-check"></i><b>3</b> Regresja</a><ul>
<li class="chapter" data-level="3.1" data-path="regresja.html"><a href="regresja.html#regresja-prosta"><i class="fa fa-check"></i><b>3.1</b> Regresja prosta</a><ul>
<li class="chapter" data-level="3.1.1" data-path="regresja.html"><a href="regresja.html#zadanie"><i class="fa fa-check"></i><b>3.1.1</b> Zadanie</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="regresja.html"><a href="regresja.html#regresja-wieloraka"><i class="fa fa-check"></i><b>3.2</b> Regresja wieloraka</a><ul>
<li class="chapter" data-level="3.2.1" data-path="regresja.html"><a href="regresja.html#zadanie-1"><i class="fa fa-check"></i><b>3.2.1</b> Zadanie</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="grupowanie.html"><a href="grupowanie.html"><i class="fa fa-check"></i><b>4</b> Grupowanie</a><ul>
<li class="chapter" data-level="4.1" data-path="grupowanie.html"><a href="grupowanie.html#metoda-k-srednich"><i class="fa fa-check"></i><b>4.1</b> Metoda k-średnich</a></li>
<li class="chapter" data-level="4.2" data-path="grupowanie.html"><a href="grupowanie.html#metoda-hierarchiczna"><i class="fa fa-check"></i><b>4.2</b> Metoda hierarchiczna</a><ul>
<li class="chapter" data-level="4.2.1" data-path="grupowanie.html"><a href="grupowanie.html#zadania"><i class="fa fa-check"></i><b>4.2.1</b> Zadania</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="klasyfikacja.html"><a href="klasyfikacja.html"><i class="fa fa-check"></i><b>5</b> Klasyfikacja</a><ul>
<li class="chapter" data-level="5.1" data-path="klasyfikacja.html"><a href="klasyfikacja.html#drzewa-klasyfikacyjne"><i class="fa fa-check"></i><b>5.1</b> Drzewa klasyfikacyjne</a></li>
<li class="chapter" data-level="5.2" data-path="klasyfikacja.html"><a href="klasyfikacja.html#knn"><i class="fa fa-check"></i><b>5.2</b> KNN</a><ul>
<li class="chapter" data-level="5.2.1" data-path="klasyfikacja.html"><a href="klasyfikacja.html#zadanie-2"><i class="fa fa-check"></i><b>5.2.1</b> Zadanie</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="materiay-z-zajec.html"><a href="materiay-z-zajec.html"><i class="fa fa-check"></i><b>6</b> Materiały z zajęć</a><ul>
<li class="chapter" data-level="6.1" data-path="materiay-z-zajec.html"><a href="materiay-z-zajec.html#section"><i class="fa fa-check"></i><b>6.1</b> 28.10.2018</a></li>
<li class="chapter" data-level="6.2" data-path="materiay-z-zajec.html"><a href="materiay-z-zajec.html#section-1"><i class="fa fa-check"></i><b>6.2</b> 18.11.2018</a></li>
<li class="chapter" data-level="6.3" data-path="materiay-z-zajec.html"><a href="materiay-z-zajec.html#section-2"><i class="fa fa-check"></i><b>6.3</b> 16.12.2018</a></li>
<li class="chapter" data-level="6.4" data-path="materiay-z-zajec.html"><a href="materiay-z-zajec.html#section-3"><i class="fa fa-check"></i><b>6.4</b> 26.01.2019</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Metody przetwarzania i analizy danych w R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regresja" class="section level1">
<h1><span class="header-section-number">3</span> Regresja</h1>
<p>Metody regresji pozwalają na analizowanie zależności przyczynowo-skutkowych.</p>
<p>Na początku pracy wczytujemy biblioteki <code>tidyverse</code>, <code>readxl</code> oraz wyłączamy notację naukową.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(readxl)

<span class="kw">options</span>(<span class="dt">scipen =</span> <span class="dv">100</span>)</code></pre></div>
<div id="regresja-prosta" class="section level2">
<h2><span class="header-section-number">3.1</span> Regresja prosta</h2>
<p>Na podstawie <a href="data/Salary_Data.csv">danych</a> dotyczących informacji o doświadczeniu i wynagrodzeniu pracowników zbuduj model określający ‘widełki’ dla potencjalnych pracowników o doświadczeniu równym 8, 10 i 11 lat.</p>
<p>Wczytujemy dane i sprawdzamy czy nie występują zera bądź braki danych z użyciem funkcji <code>summary()</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dane &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/Salary_Data.csv&quot;</span>)

<span class="kw">summary</span>(dane)</code></pre></div>
<pre><code>##  YearsExperience      Salary      
##  Min.   : 1.100   Min.   : 37731  
##  1st Qu.: 3.200   1st Qu.: 56721  
##  Median : 4.700   Median : 65237  
##  Mean   : 5.313   Mean   : 76003  
##  3rd Qu.: 7.700   3rd Qu.:100545  
##  Max.   :10.500   Max.   :122391</code></pre>
<p>Następnie stworzymy wykres.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(dane)</code></pre></div>
<p><img src="Wawrowski_ADR_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Najprostszym sposobem wizualizacji jest wykorzystanie funkcji <code>plot()</code>, niemniej taki wykres nie jest najpiękniejszy i trudno się go formatuje. Dużo lepiej skorzystać z pakietu <code>ggplot2</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(dane, <span class="kw">aes</span>(<span class="dt">x=</span>YearsExperience, <span class="dt">y=</span>Salary)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">colour =</span> <span class="st">&quot;blue&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Doświadczenie&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Pensja&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlim</span>(<span class="dv">0</span>,<span class="dv">12</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">ylim</span>(<span class="dv">35000</span>, <span class="dv">126000</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_bw</span>()</code></pre></div>
<p><img src="Wawrowski_ADR_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>W argumentach funkcji <code>ggplot()</code> podajemy co wizualizujemy, natomiast sposób prezentacji ustalany jest przez funkcje <code>geom</code>. Funkcje <code>xlab()</code> i <code>ylab()</code> określają etykiety osi, a <code>xlim()</code> i <code>ylim()</code> wartości graniczne. Funkcje rozpoczynające się od <code>theme_</code> określają wygląd wykresu.</p>
<p>Modelowanie rozpoczynamy od określenia zmiennej zależnej i niezależnej.</p>
<ul>
<li>zmienna zależna/objaśniana: pensja</li>
<li>zmienna niezależna/objaśniająca: doświadczenie</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">lm</span>(Salary <span class="op">~</span><span class="st"> </span>YearsExperience, <span class="dt">data =</span> dane)
<span class="kw">summary</span>(model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Salary ~ YearsExperience, data = dane)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7958.0 -4088.5  -459.9  3372.6 11448.0 
## 
## Coefficients:
##                 Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept)      25792.2     2273.1   11.35     0.00000000000551 ***
## YearsExperience   9450.0      378.8   24.95 &lt; 0.0000000000000002 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5788 on 28 degrees of freedom
## Multiple R-squared:  0.957,  Adjusted R-squared:  0.9554 
## F-statistic: 622.5 on 1 and 28 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<ul>
<li>b1 = 9450 - wzrost doświadczenia o rok powoduje przeciętny wzrost pensji o 9450 zł</li>
<li>b0 = 25792,2 - pracownik o doświadczeniu 0 lat uzyska pensję w wysokości 25792,2 zł</li>
</ul>
<p>Resztowy błąd standardowy Su wynosi 5788, co oznacza wartości z modelu różnią się od rzeczywistości średnio o +/- 5788 zł</p>
<p>R2 = 0,957 - model wyjaśnia 96% zmienności pensji</p>
<p>Dokonujemy wyznaczenia wartości teoretycznych dla kilku wybranych lat.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nowiPracownicy &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">YearsExperience=</span><span class="kw">c</span>(<span class="dv">8</span>,<span class="dv">10</span>,<span class="dv">11</span>))

<span class="kw">predict</span>(model, nowiPracownicy)</code></pre></div>
<pre><code>##        1        2        3 
## 101391.9 120291.8 129741.8</code></pre>
<p>Tym sposobem uzyskujemy następujące widełki:</p>
<ul>
<li>pracownik o stażu 8 lat - proponowana pensja 101391,9 zł +/- 5788 zł</li>
<li>pracownik o stażu 10 lat - proponowana pensja 120291,8 zł +/- 5788 zł</li>
<li>pracownik o stażu 11 lat - proponowana pensja 129741,8 zł +/- 5788 zł</li>
</ul>
<div id="zadanie" class="section level3">
<h3><span class="header-section-number">3.1.1</span> Zadanie</h3>
<p>Dla danych dotyczących <a href="data/sklep77.csv">sklepu nr 77</a> opracuj model zależności sprzedaży od liczby klientów. Ile wynosi teoretyczna sprzedaż w dniach, w których liczba klientów będzie wynosiła 560, 740, 811 oraz 999 osób?</p>
</div>
</div>
<div id="regresja-wieloraka" class="section level2">
<h2><span class="header-section-number">3.2</span> Regresja wieloraka</h2>
<p>Na podstawie danych dotyczących <a href="data/pracownicy.xlsx">zatrudnienia</a> opracuj model, w którym zmienną zależną jest bieżące wynagrodzenie. Jaka cecha ma największy wpływ na tę wartość?</p>
<p>Opis zbioru:</p>
<ul>
<li>id - kod pracownika</li>
<li>plec - płeć pracownika (0 - mężczyzna, 1 - kobieta)</li>
<li>data_urodz - data urodzenia</li>
<li>edukacja - wykształcenie (w latach nauki)</li>
<li>kat_pracownika - grupa pracownicza (1 - ochroniarz, 2 - urzędnik, 3 - menedżer)</li>
<li>bwynagrodzenie - bieżące wynagrodzenie</li>
<li>pwynagrodzenie - początkowe wynagrodzenie</li>
<li>staz - staż pracy (w miesiącach)</li>
<li>doswiadczenie - poprzednie zatrudnienie (w miesiącach)</li>
<li>zwiazki - przynależność do związków zawodowych (0 - nie, 1 - tak)</li>
<li>wiek - wiek (w latach)</li>
</ul>
<p>Wczytanie danych.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pracownicy &lt;-<span class="st"> </span><span class="kw">read_xlsx</span>(<span class="st">&quot;data/pracownicy.xlsx&quot;</span>)

pracownicy2 &lt;-<span class="st"> </span>pracownicy <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(wiek)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>id, <span class="op">-</span>data_urodz) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">plec=</span><span class="kw">as.factor</span>(plec),
         <span class="dt">kat_pracownika=</span><span class="kw">as.factor</span>(kat_pracownika),
         <span class="dt">zwiazki=</span><span class="kw">as.factor</span>(zwiazki))

<span class="kw">summary</span>(pracownicy2)</code></pre></div>
<pre><code>##  plec       edukacja     kat_pracownika bwynagrodzenie   pwynagrodzenie 
##  0:257   Min.   : 8.00   1:362          Min.   : 15750   Min.   : 9000  
##  1:216   1st Qu.:12.00   2: 27          1st Qu.: 24000   1st Qu.:12450  
##          Median :12.00   3: 84          Median : 28800   Median :15000  
##          Mean   :13.49                  Mean   : 34418   Mean   :17009  
##          3rd Qu.:15.00                  3rd Qu.: 37050   3rd Qu.:17490  
##          Max.   :21.00                  Max.   :135000   Max.   :79980  
##       staz       doswiadczenie    zwiazki      wiek      
##  Min.   :63.00   Min.   :  0.00   0:369   Min.   :24.00  
##  1st Qu.:72.00   1st Qu.: 19.00   1:104   1st Qu.:30.00  
##  Median :81.00   Median : 55.00           Median :33.00  
##  Mean   :81.14   Mean   : 95.95           Mean   :38.67  
##  3rd Qu.:90.00   3rd Qu.:139.00           3rd Qu.:47.00  
##  Max.   :98.00   Max.   :476.00           Max.   :66.00</code></pre>
<p>W zmiennej wiek występował brak danych, który został usunięty. Usunięto także kolumny, które nie przydadzą się w modelowaniu. Ponadto dokonujemy przekształcenia typu cech, które są jakościowe (płeć, kat_pracownika, zwiazki) z typu liczbowego na czynnik/faktor, który będzie poprawnie interpretowany przez model.</p>
<p>W modelu zmienna zależna to <code>bwynagrodzenie</code>, natomiast jako zmienne niezależne bierzemy pod uwagę wszystkie pozostałe cechy.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">lm</span>(bwynagrodzenie <span class="op">~</span><span class="st"> </span>., pracownicy2)
<span class="kw">summary</span>(model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = bwynagrodzenie ~ ., data = pracownicy2)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -23185  -3041   -705   2591  46295 
## 
## Coefficients:
##                    Estimate  Std. Error t value             Pr(&gt;|t|)    
## (Intercept)     -4764.87418  3590.49652  -1.327              0.18514    
## plec1           -1702.43743   796.51779  -2.137              0.03309 *  
## edukacja          482.43603   160.83977   2.999              0.00285 ** 
## kat_pracownika2  6643.17910  1638.06138   4.056  0.00005869172850407 ***
## kat_pracownika3 11169.64519  1372.73990   8.137  0.00000000000000377 ***
## pwynagrodzenie      1.34021     0.07317  18.315 &lt; 0.0000000000000002 ***
## staz              154.50876    31.65933   4.880  0.00000145958620443 ***
## doswiadczenie     -15.77375     5.78369  -2.727              0.00663 ** 
## zwiazki1        -1011.55276   787.80884  -1.284              0.19978    
## wiek              -64.78787    47.88015  -1.353              0.17668    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6809 on 463 degrees of freedom
## Multiple R-squared:  0.8444, Adjusted R-squared:  0.8414 
## F-statistic: 279.1 on 9 and 463 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>Tak zbudowany model wyjaśnia 84% zmienności bieżącego wynagrodzenia, ale nie wszystkie zmienne są w tym modelu istotne.</p>
<p>Parametry regresji mają następujące interpretacje:</p>
<ul>
<li>plec1 - kobiety zarabiają przeciętnie o 1702,44 zł mniej niż mężczyźni,</li>
<li>edukacja - wzrost liczby lat nauki o rok powoduje średni wzrost bieżącego wynagrodzenia o 482,44 zł</li>
<li>kat_pracownika2 - pracownicy o kodzie 2 (urzędnik) zarabiają średnio o 6643,18 zł więcej niż pracownik o kodzie 1 (ochroniarz)</li>
<li>kat_pracownika2 - pracownicy o kodzie 3 (menedżer) zarabiają średnio o 11169,65 zł więcej niż pracownik o kodzie 1 (ochroniarz)</li>
<li>pwynagrodzenie - wzrost początkowego wynagrodzenia o 1 zł powoduje przeciętny wzrost bieżącego wynagrodzenia o 1,34 zł</li>
<li>staz - wzrost stażu pracy o miesiąc skutkuje przeciętnym wzrostem bieżącego wynagrodzenia o 154,51 zł</li>
<li>doswiadcznie - wzrost doświadczenia o miesiąc powoduje średni spadek bieżącego wynagrodzenia o 15,77 zł</li>
<li>zwiazki1 - pracownicy należący do związków zawodowych zarabiają średnio o 1011,55 zł mniej aniżeli pracownicy, którzy do związków nie zależą</li>
<li>wiek - wzrost wieku pracownika o 1 rok to przeciętnym spadek bieżącego wynagrodzenia o 64,79 zł</li>
</ul>
<p>Wszystkie te zależności obowiązują przy założeniu <em>ceteris paribus</em> - przy pozostałych warunkach niezmienionych.</p>
<p>Ten model wymaga oczywiście ulepszenie do czego wykorzystamy m.in. pakiet <a href="https://cran.r-project.org/web/packages/olsrr/index.html">olsrr</a>.</p>
<p>Pierwszą kwestią, którą się zajmiemy jest współliniowość zmiennych. W regresji zmienne objaśniające powinny być jak najbardziej skorelowane ze zmienną objaśnianą, a możliwie nieskorelowane ze sobą. W związku z tym wybieramy ze zbioru wyłącznie cechy ilościowe, dla którym wyznaczymy współczynnik korelacji liniowej Pearsona.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(corrplot)
<span class="kw">library</span>(olsrr)

korelacje &lt;-<span class="st"> </span>pracownicy2 <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span><span class="kw">c</span>(plec, kat_pracownika, zwiazki)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">cor</span>()

<span class="kw">corrplot</span>(korelacje, <span class="dt">method =</span> <span class="st">&quot;number&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;upper&quot;</span>)</code></pre></div>
<p><img src="Wawrowski_ADR_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Możemy zauważyć, że wartości bieżącego wynagrodzenia są najsilniej skorelowane w wartościami wynagrodzenia początkowego. Także doświadczenie i wiek są silnie ze sobą związane, co może sugerować, że obie zmienne wnoszą do modelu podobną informację.</p>
<p>W związku z tym powinniśmy wyeliminować niektóre zmienne z modelu pozostawiając te najważniejsze. Wyróżnia się trzy podejścia do tego zagadnienia:</p>
<ul>
<li>ekspercki dobór cech,</li>
<li>budowa wszystkich możliwych modeli i wybór najlepszego według określonego kryterium,</li>
<li>regresja krokowa.</li>
</ul>
<p>W przypadku budowy wszystkich możliwych modeli należy pamiętać o rosnącej wykładniczo liczbie modeli - <span class="math inline">\(2^p-1\)</span>, gdzie <span class="math inline">\(p\)</span> oznacza liczbę zmiennych objaśniających. w rozważanym przypadku liczba modeli wynosi 255.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">wszystkie_modele &lt;-<span class="st"> </span><span class="kw">ols_step_all_possible</span>(model)</code></pre></div>
<p>W uzyskanym zbiorze danych są informacje o numerze modelu, liczbie użytych zmiennych, nazwie tych zmiennych oraz wiele miar jakości. Te, które warto wziąć pod uwagę to przede wszystkim:</p>
<ul>
<li><code>rsquare</code> - współczynnik R-kwadrat,</li>
<li><code>aic</code> - kryterium informacyjne Akaike,</li>
<li><code>msep</code> - błąd średniokwadratowy predykcji.</li>
</ul>
<p>Najwyższa wartość współczynnika <span class="math inline">\(R^2\)</span> związana jest z modelem zawierającym wszystkie dostępne zmienne objaśniające. Jest to pewna niedoskonałość tej miary, która rośnie wraz z liczbą zmiennych w modelu, nawet jeśli te zmienne nie są istotne.</p>
<p>W przypadku kryteriów informacyjnych oraz błędu średniokwadratowego interesują nas jak najmniejsze wartości. Wówczas jako najlepszy należy wskazać model nr 219 zawierający 6 zmiennych objaśniających.</p>
<p>Metodą, która także pozwoli uzyskać optymalny model, ale przy mniejszym obciążeniu obliczeniowym jest regresja krokowa polegająca na krokowym budowaniu modelu.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ols_step_both_aic</span>(model)</code></pre></div>
<pre><code>## Stepwise Selection Method 
## -------------------------
## 
## Candidate Terms: 
## 
## 1 . plec 
## 2 . edukacja 
## 3 . kat_pracownika 
## 4 . pwynagrodzenie 
## 5 . staz 
## 6 . doswiadczenie 
## 7 . zwiazki 
## 8 . wiek 
## 
## 
## Variables Entered/Removed: 
## 
## - pwynagrodzenie added 
## - kat_pracownika added 
## - doswiadczenie added 
## - staz added 
## - edukacja added 
## - plec added 
## 
## No more variables to be added or removed.</code></pre>
<pre><code>## 
## 
##                                            Stepwise Summary                                            
## -----------------------------------------------------------------------------------------------------
## Variable           Method       AIC             RSS               Sum Sq          R-Sq      Adj. R-Sq 
## -----------------------------------------------------------------------------------------------------
## pwynagrodzenie    addition    9862.260    31053506813.535    106862706669.340    0.77484      0.77436 
## kat_pracownika    addition    9786.152    26215474648.689    111700738834.186    0.80992      0.80870 
## doswiadczenie     addition    9743.487    23853248017.651    114062965465.224    0.82705      0.82557 
## staz              addition    9719.469    22576592070.620    115339621412.255    0.83630      0.83455 
## edukacja          addition    9707.338    21912088629.084    116004124853.791    0.84112      0.83907 
## plec              addition    9703.188    21629051655.016    116287161827.859    0.84317      0.84081 
## -----------------------------------------------------------------------------------------------------</code></pre>
<p>Otrzymany w ten sposób model jest tożsamy z modelem charakteryzującym się najlepszymi miarami jakości spośród zbioru wszystkich możliwych modeli:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">wybrany_model &lt;-<span class="st"> </span><span class="kw">lm</span>(bwynagrodzenie <span class="op">~</span><span class="st"> </span>pwynagrodzenie <span class="op">+</span><span class="st"> </span>kat_pracownika <span class="op">+</span><span class="st"> </span>doswiadczenie <span class="op">+</span><span class="st"> </span>staz <span class="op">+</span><span class="st"> </span>plec <span class="op">+</span><span class="st"> </span>edukacja, <span class="dt">data =</span> pracownicy2)
<span class="kw">summary</span>(wybrany_model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = bwynagrodzenie ~ pwynagrodzenie + kat_pracownika + 
##     doswiadczenie + staz + plec + edukacja, data = pracownicy2)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -22922  -3300   -673   2537  46524 
## 
## Coefficients:
##                  Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept)     -6547.147   3402.860  -1.924              0.05496 .  
## pwynagrodzenie      1.342      0.073  18.382 &lt; 0.0000000000000002 ***
## kat_pracownika2  6734.992   1631.122   4.129   0.0000431843301918 ***
## kat_pracownika3 11226.635   1368.413   8.204   0.0000000000000023 ***
## doswiadczenie     -22.302      3.571  -6.246   0.0000000009514655 ***
## staz              147.865     31.461   4.700   0.0000034337703087 ***
## plec1           -1878.949    761.703  -2.467              0.01399 *  
## edukacja          501.391    160.270   3.128              0.00187 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6820 on 465 degrees of freedom
## Multiple R-squared:  0.8432, Adjusted R-squared:  0.8408 
## F-statistic: 357.1 on 7 and 465 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>Uzyskany model charakteryzuje się mniejszym błędem standardowym od modelu ze wszystkimi zmiennymi i tylko jedną nieistotną zmienną. Wyraz wolny (Intercept) nie musi być istotny w modelu.</p>
<p>Wróćmy jeszcze na chwilę do tematu współliniowości zmiennych objaśniających:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ols_vif_tol</span>(wybrany_model)</code></pre></div>
<pre><code>## # A tibble: 7 x 3
##   Variables       Tolerance   VIF
##   &lt;chr&gt;               &lt;dbl&gt; &lt;dbl&gt;
## 1 pwynagrodzenie      0.298  3.36
## 2 kat_pracownika2     0.687  1.46
## 3 kat_pracownika3     0.360  2.78
## 4 doswiadczenie       0.705  1.42
## 5 staz                0.986  1.01
## 6 plec1               0.683  1.46
## 7 edukacja            0.461  2.17</code></pre>
<p>Współczynnik tolerancji wskazuje na procent niewyjaśnionej zmienności danej zmiennej przez pozostałe zmienne objaśniające. Przykładowo współczynnik tolerancji dla początkowego wynagrodzenia wynosi 0,2980, co oznacza, że 30% zmienności początkowego wynagrodzenia nie jest wyjaśnione przez pozostałe zmienne w modelu. Z kolei współczynnik VIF jest obliczany na podstawie wartości współczynnika tolerancji i wskazuje o ile wariancja szacowanego współczynnika regresji jest podwyższona z powodu współliniowości danej zmiennej objaśniającej z pozostałymi zmiennymi objaśniającymi. Wartość współczynnika VIF powyżej 4 należy uznać za wskazującą na współliniowość. W analizowanym przypadku takie zmienne nie występują.</p>
<p>Ocena siły wpływu poszczególnych zmiennych objaśniających na zmienną objaśnianą w oryginalnej postaci modelu nie jest możliwa. Należy wyznaczyć standaryzowane współczynniki beta, które wyliczane są na danych standaryzowanych, czyli takich, które są pozbawione jednostek i cechują się średnią równą 0, a odchyleniem standardowym równym 1. Standaryzacja ma sens tylko dla cech numerycznych, w związku z czym korzystamy z funkcji <code>mutate_if()</code>, która jako pierwszy argument przyjmuje warunek, który ma być spełniony, aby była zastosowane przekształcenie podawane jako drugi argument.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pracownicy2_std &lt;-<span class="st"> </span>pracownicy2 <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate_if</span>(is.numeric, scale)

wybrany_model_std &lt;-<span class="st"> </span><span class="kw">lm</span>(bwynagrodzenie <span class="op">~</span><span class="st"> </span>pwynagrodzenie <span class="op">+</span><span class="st"> </span>kat_pracownika <span class="op">+</span><span class="st"> </span>
<span class="st">                          </span>doswiadczenie <span class="op">+</span><span class="st"> </span>staz <span class="op">+</span><span class="st"> </span>plec <span class="op">+</span><span class="st"> </span>edukacja, <span class="dt">data =</span> pracownicy2_std)
<span class="kw">summary</span>(wybrany_model_std)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = bwynagrodzenie ~ pwynagrodzenie + kat_pracownika + 
##     doswiadczenie + staz + plec + edukacja, data = pracownicy2_std)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.34098 -0.19306 -0.03939  0.14841  2.72171 
## 
## Coefficients:
##                 Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept)     -0.08893    0.03144  -2.828              0.00488 ** 
## pwynagrodzenie   0.61842    0.03364  18.382 &lt; 0.0000000000000002 ***
## kat_pracownika2  0.39400    0.09542   4.129   0.0000431843301918 ***
## kat_pracownika3  0.65677    0.08005   8.204   0.0000000000000023 ***
## doswiadczenie   -0.13657    0.02187  -6.246   0.0000000009514655 ***
## staz             0.08691    0.01849   4.700   0.0000034337703087 ***
## plec1           -0.10992    0.04456  -2.467              0.01399 *  
## edukacja         0.08464    0.02706   3.128              0.00187 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.399 on 465 degrees of freedom
## Multiple R-squared:  0.8432, Adjusted R-squared:  0.8408 
## F-statistic: 357.1 on 7 and 465 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>Spośród cech ilościowych największy wpływ na zmienną objaśnianą mają wartości wynagrodzenia początkowego, staż, edukacja i na końcu doświadczenie.</p>
<p>Reszty czyli różnice pomiędzy obserwowanymi wartościami zmiennej objaśnianej, a wartościami wynikającymi z modelu w klasycznej metodzie najmniejszych kwadratów powinny być zbliżone do rozkładu normalnego. Oznacza to, że najwięcej reszt powinno skupiać się wokół zerowych różnic, natomiast jak najmniej powinno być wartości modelowych znacznie różniących się od tych rzeczywistych.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ols_plot_resid_hist</span>(wybrany_model)</code></pre></div>
<p><img src="Wawrowski_ADR_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Reszty w naszym modelu wydają się być zbliżone do rozkładu normalnego. Jednoznaczną odpowiedź da jednak odpowiedni test.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ols_test_normality</span>(wybrany_model)</code></pre></div>
<pre><code>## -----------------------------------------------
##        Test             Statistic       pvalue  
## -----------------------------------------------
## Shapiro-Wilk              0.868          0.0000 
## Kolmogorov-Smirnov        0.1092         0.0000 
## Cramer-von Mises         42.5504         0.0001 
## Anderson-Darling         13.0233         0.0000 
## -----------------------------------------------</code></pre>
<p>Hipoteza zerowa w tych testach mówi o zgodności rozkładu reszt z rozkładem normalnym. Na podstawie wartości p, które są mniejsze od <span class="math inline">\(\alpha=0,05\)</span> stwierdzamy, że są podstawy do odrzucenia tej hipotezy czyli reszty z naszego modelu nie mają rozkładu normalnego. W diagnostyce przyczyn takiego stanu rzeczy pomoże nam wykres kwantyl-kwantyl:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ols_plot_resid_qq</span>(wybrany_model)</code></pre></div>
<p><img src="Wawrowski_ADR_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Gdyby wszystkie punkty leżały na prostej to oznaczałoby to normalność rozkładu reszt. Tymczasem po lewej i prawej stronie tego wykresu znajdują się potencjalne wartości odstające, które znacznie wpływają na rozkład reszt modelu.</p>
<p>Wartości odstające można ustalić na podstawie wielu kryteriów. Do jednych z najbardziej popularnych należy odległość Cooka:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cook &lt;-<span class="st"> </span><span class="kw">ols_plot_cooksd_bar</span>(wybrany_model)</code></pre></div>
<p><img src="Wawrowski_ADR_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Przypisanie tej funkcji do obiektu zwraca nam tabelę z numerami zidentyfikowanych obserwacji wpływowych. W przypadku odległości Cooka jest to 35 obserwacji.</p>
<p>Inną miarą są reszty studentyzowane.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">stud3 &lt;-<span class="st"> </span><span class="kw">ols_plot_resid_stud</span>(wybrany_model)</code></pre></div>
<p><img src="Wawrowski_ADR_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>Wyżej wykorzystana funkcja jako kryterium odstawania przyjmuje wartość 3 identyfikując 10 obserwacji wpływowych. Z kolei dodanie do powyższej funkcji przyrostka <em>fit</em> powoduje przyjęcie jako granicy wartości równej 2.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">obs_wplyw &lt;-<span class="st"> </span><span class="kw">ols_plot_resid_stud_fit</span>(wybrany_model)</code></pre></div>
<p><img src="Wawrowski_ADR_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>W ten sposób zostało zidentyfikowanych 22 obserwacji odstających. Korzystając z odległości Cooka wyeliminujemy obserwacje odstające ze zbioru:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nr_obs_wplyw &lt;-<span class="st"> </span>cook<span class="op">$</span>outliers<span class="op">$</span>observation

bez_obs_wplyw &lt;-<span class="st"> </span>pracownicy2[<span class="op">-</span>nr_obs_wplyw,]

wybrany_model_out &lt;-<span class="st"> </span><span class="kw">lm</span>(bwynagrodzenie <span class="op">~</span><span class="st"> </span>pwynagrodzenie <span class="op">+</span><span class="st"> </span>kat_pracownika <span class="op">+</span><span class="st"> </span>doswiadczenie <span class="op">+</span><span class="st"> </span>staz <span class="op">+</span><span class="st"> </span>plec <span class="op">+</span><span class="st"> </span>edukacja, 
                        <span class="dt">data =</span> bez_obs_wplyw)
<span class="kw">summary</span>(wybrany_model_out)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = bwynagrodzenie ~ pwynagrodzenie + kat_pracownika + 
##     doswiadczenie + staz + plec + edukacja, data = bez_obs_wplyw)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -12591.2  -2696.4   -564.8   2263.0  14704.1 
## 
## Coefficients:
##                   Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept)     -3756.8288  2381.5361  -1.577             0.115420    
## pwynagrodzenie      1.3696     0.0676  20.260 &lt; 0.0000000000000002 ***
## kat_pracownika2  6480.6971  1049.9539   6.172   0.0000000015569534 ***
## kat_pracownika3  9791.5000  1059.4980   9.242 &lt; 0.0000000000000002 ***
## doswiadczenie     -18.5808     2.3229  -7.999   0.0000000000000117 ***
## staz              116.3809    20.9704   5.550   0.0000000501086186 ***
## plec1           -1616.6030   505.1391  -3.200             0.001475 ** 
## edukacja          397.7652   105.8146   3.759             0.000194 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4271 on 430 degrees of freedom
## Multiple R-squared:  0.894,  Adjusted R-squared:  0.8923 
## F-statistic: 518.3 on 7 and 430 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>Model dopasowany na takim zbiorze charakteryzuje się dużo mniejszym błędem standardowym oraz wyższym współczynnikiem <span class="math inline">\(R^2\)</span>. Sprawdźmy w takim razie normalność reszt.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ols_plot_resid_qq</span>(wybrany_model_out)</code></pre></div>
<p><img src="Wawrowski_ADR_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>Wykres kwantyl-kwantyl wygląda już dużo lepiej, ale dla pewności przeprowadzimy testy statystyczne.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ols_test_normality</span>(wybrany_model_out)</code></pre></div>
<pre><code>## -----------------------------------------------
##        Test             Statistic       pvalue  
## -----------------------------------------------
## Shapiro-Wilk              0.9696         0.0000 
## Kolmogorov-Smirnov        0.0667         0.0405 
## Cramer-von Mises         38.1644         0.0001 
## Anderson-Darling          3.5421         0.0000 
## -----------------------------------------------</code></pre>
<p>Tylko jeden test wskazał zgodność rozkładu reszt z rozkładem normalnym.</p>
<div id="zadanie-1" class="section level3">
<h3><span class="header-section-number">3.2.1</span> Zadanie</h3>
<p>Na podstawie zbioru dotyczącego <a href="data/50_Startups.csv">50 startupów</a> określ jakie czynniki wpływają na przychód startupów. Na zajęciach 27.04.2019 r. przedyskutujemy wyniki.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">startupy &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/50_Startups.csv&quot;</span>)

<span class="kw">summary</span>(startupy)</code></pre></div>
<pre><code>##    R.D.Spend      Administration   Marketing.Spend         State   
##  Min.   :     0   Min.   : 51283   Min.   :     0   California:17  
##  1st Qu.: 39936   1st Qu.:103731   1st Qu.:129300   Florida   :16  
##  Median : 73051   Median :122700   Median :212716   New York  :17  
##  Mean   : 73722   Mean   :121345   Mean   :211025                  
##  3rd Qu.:101603   3rd Qu.:144842   3rd Qu.:299469                  
##  Max.   :165349   Max.   :182646   Max.   :471784                  
##      Profit      
##  Min.   : 14681  
##  1st Qu.: 90139  
##  Median :107978  
##  Mean   :112013  
##  3rd Qu.:139766  
##  Max.   :192262</code></pre>
<p>Podsumowanie danych pokazuje występowanie zer w wartościach zmiennych R.D.Spend i Marketing.Spend - należy je wyeliminować.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">startupy &lt;-<span class="st"> </span>startupy <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(R.D.Spend <span class="op">!=</span><span class="st"> </span><span class="dv">0</span>, Marketing.Spend <span class="op">!=</span><span class="st"> </span><span class="dv">0</span>)</code></pre></div>
<p>Na tak przygotowanym zbiorze możemy dopasować model ze wszystkimi zmiennymi.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">lm</span>(Profit <span class="op">~</span><span class="st"> </span>., <span class="dt">data=</span>startupy)
<span class="kw">summary</span>(model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Profit ~ ., data = startupy)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -15464  -4887  -1424   5550  13560 
## 
## Coefficients:
##                    Estimate  Std. Error t value             Pr(&gt;|t|)    
## (Intercept)     59773.09290  6126.19072   9.757     0.00000000000391 ***
## R.D.Spend           0.77507     0.03909  19.828 &lt; 0.0000000000000002 ***
## Administration     -0.05759     0.04515  -1.275                0.210    
## Marketing.Spend     0.02102     0.01528   1.376                0.176    
## StateFlorida    -1752.43437  2744.96836  -0.638                0.527    
## StateNew York   -1597.22937  2764.85338  -0.578                0.567    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7503 on 40 degrees of freedom
## Multiple R-squared:  0.9613, Adjusted R-squared:  0.9565 
## F-statistic: 198.7 on 5 and 40 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>Jedyną istotną zmienną objaśniającą jest cecha R.D.Spend. W związku z tym używamy funkcji krokowej metody doboru zmiennych w celu znalezienia istotnych czynników wpływających na przychód startupu.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ols_step_both_p</span>(model)</code></pre></div>
<pre><code>## Stepwise Selection Method   
## ---------------------------
## 
## Candidate Terms: 
## 
## 1. R.D.Spend 
## 2. Administration 
## 3. Marketing.Spend 
## 4. State 
## 
## We are selecting variables based on p value...
## 
## Variables Entered/Removed: 
## 
## - R.D.Spend added 
## - Administration added 
## 
## No more variables to be added/removed.
## 
## 
## Final Model Output 
## ------------------
## 
##                            Model Summary                             
## --------------------------------------------------------------------
## R                       0.979       RMSE                   7427.091 
## R-Squared               0.959       Coef. Var                 6.344 
## Adj. R-Squared          0.957       MSE                55161684.725 
## Pred R-Squared          0.953       MAE                    6057.542 
## --------------------------------------------------------------------
##  RMSE: Root Mean Square Error 
##  MSE: Mean Square Error 
##  MAE: Mean Absolute Error 
## 
##                                      ANOVA                                       
## --------------------------------------------------------------------------------
##                        Sum of                                                   
##                       Squares        DF        Mean Square       F         Sig. 
## --------------------------------------------------------------------------------
## Regression    55818532409.384         2    27909266204.692    505.954    0.0000 
## Residual       2371952443.176        43       55161684.725                      
## Total         58190484852.560        45                                         
## --------------------------------------------------------------------------------
## 
##                                         Parameter Estimates                                          
## ----------------------------------------------------------------------------------------------------
##          model         Beta    Std. Error    Std. Beta      t        Sig         lower        upper 
## ----------------------------------------------------------------------------------------------------
##    (Intercept)    62996.044      5252.182                 11.994    0.000    52404.009    73588.078 
##      R.D.Spend        0.814         0.026        0.989    31.507    0.000        0.762        0.866 
## Administration       -0.079         0.042       -0.059    -1.875    0.068       -0.164        0.006 
## ----------------------------------------------------------------------------------------------------</code></pre>
<pre><code>## 
##                                  Stepwise Selection Summary                                   
## ---------------------------------------------------------------------------------------------
##                            Added/                   Adj.                                         
## Step       Variable       Removed     R-Square    R-Square     C(p)       AIC         RMSE       
## ---------------------------------------------------------------------------------------------
##    1      R.D.Spend       addition       0.956       0.955    3.5750    957.0424    7636.5800    
##    2    Administration    addition       0.959       0.957    2.1290    955.4259    7427.0913    
## ---------------------------------------------------------------------------------------------</code></pre>
<p>Algorytm proponuje tylko dwie cechy w modelu R.D.Spend i Administration.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model_2zm &lt;-<span class="st"> </span><span class="kw">lm</span>(Profit <span class="op">~</span><span class="st"> </span>R.D.Spend <span class="op">+</span><span class="st"> </span>Administration, <span class="dt">data=</span>startupy)
<span class="kw">summary</span>(model_2zm)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Profit ~ R.D.Spend + Administration, data = startupy)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -16632  -4867  -2488   6280  14410 
## 
## Coefficients:
##                   Estimate  Std. Error t value             Pr(&gt;|t|)    
## (Intercept)    62996.04359  5252.18190  11.994  0.00000000000000262 ***
## R.D.Spend          0.81412     0.02584  31.507 &lt; 0.0000000000000002 ***
## Administration    -0.07897     0.04211  -1.875               0.0675 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7427 on 43 degrees of freedom
## Multiple R-squared:  0.9592, Adjusted R-squared:  0.9573 
## F-statistic:   506 on 2 and 43 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>W związku z czym stwierdzamy, że tylko te dwie cechy wpływają istotnie na przychód - wydatki na R&amp;D wpływają na niego pozytywnie, a na administracje ujemnie.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="testowanie-hipotez.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="grupowanie.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["Wawrowski_ADR.pdf", "Wawrowski_ADR.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
